# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: goss
author: Johan Hake, Henrik Finsberg
logo: docs/_static/logo.png
copyright: "2022, Simula Research Laboratory"
only_build_toc_files: true

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force
  timeout: 3000

# Information about where the book exists on the web
repository:
  url:  https://github.com/ComputationalPhysiology/goss # Online location of your book
  branch: main


html:
  use_issues_button: true
  use_repository_button: true

parse:
  myst_enable_extensions:
    - amsmath
    - dollarmath
    - linkify

sphinx:
  config:
    bibtex_bibfiles: ["docs/refs.bib"]
    suppress_warnings: ["bibtex.duplicate_citation"]

  extra_extensions:
  - 'sphinx.ext.autodoc'
  - 'sphinx.ext.napoleon'
  - 'sphinx.ext.viewcode'
  - "sphinxcontrib.bibtex"


exclude_patterns: [".pytest_cache/*"]
