dictionaryDefinitions:
  - name: goss
    path: .cspell_dict.txt
    addWords: true
dictionaries:
  - goss
ignoreWords: [
    quickstart,
    toctree,
    maxdepth,
    genindex,
    modindex,
    mathbf,
    mathrm,
    mathbb,
    mathcal,
    operatorname,
    docname
    docnames,
  ]
