[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "pybind11>=2.9.1",
    "cmake>=3.18.2",
    "scikit-build>=0.12"
]

build-backend = "setuptools.build_meta"

[tool.cibuildwheel]
skip = ["pp*", "cp36-*"]
test-command = "python -c 'import goss'"
