[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "pybind11>=2.6.4",
    "cmake>=3.16",
    "scikit-build>=0.12"
]

build-backend = "setuptools.build_meta"


[tool.cibuildwheel]
build = ["cp{37,38,39,310}-manylinux_x86_64", "cp{37,38,39,310}-macosx_x86_64"]

test-command = "python -c 'import goss'"

[tool.cibuildwheel.linux]
before-build = "yum -y update && yum install -y boost-devel glibc-devel ninja-build cmake"

[tool.cibuildwheel.macos]
before-build = "export HOMEBREW_AUTO_UPDATING=0 && brew update && brew install ninja boost libomp"
