name: CI-cpp

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install boost
        run: sudo apt-get update && sudo apt-get install -yq libboost-all-dev pkg-config libc6-dev
      - name: Build and install goss
        run: mkdir -p build && cd build && cmake .. -DBUILD_TESTS=ON && make
      - name: Run c++ tests
        run: cd build && ctest - V