name: CI-cpp

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install boost
        run: sudo apt-get update && sudo apt-get install -yq libboost-all-dev libc6-dev cmake ninja-build
      - name: Build goss
        run: |
          cmake -B build-cpp -S cpp -DBUILD_TESTS=ON
          cmake --build build-cpp
      - name: Run c++ tests
        run: cd build-cpp && ctest - V
