name: CI-fenics

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: finsberg/fenics
    steps:
      - uses: actions/checkout@v2
      - name: Install boost
        run: apt-get update && apt-get install -yq ninja-build
      - name: Upgrade pip
        run: python -m pip install pip --upgrade
      - name: Install python dependencies
        run: python -m pip install -e ".[test,cbcbeat]"
      - name: Run tests
        run: python -m pytest
      - name: Coverage report
        uses: codecov/codecov-action@v2
        if: github.ref == 'refs/heads/main'
        with:
          fail_ci_if_error: true
          files: ./coverage.xml
