name: CI-python

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        container:
          [
            finsberg/fenics-py310,
            finsberg/fenics-py39,
            finsberg/fenics-py38,
            finsberg/fenics-py37
          ]
    container:
      image: ${{ matrix.container }}
    steps:
      - uses: actions/checkout@v2
      - name: Upgrade pip
        run: python -m pip install pip --upgrade
      - name: Install python dependencies
        run: python -m pip install -e ".[test,cbcbeat]"
      - name: Run tests
        run: python -m pytest
      - name: Coverage report
        uses: codecov/codecov-action@v2
        if: github.ref == 'refs/heads/main' && matrix.container == 'finsberg/fenics-py310'
        with:
          fail_ci_if_error: true
          files: ./coverage.xml
